### ISSUE TITLE
HgCdTe simulation

### ISSUE THREAD

**Issue by Estel-lab** [jdpetticrew/Simple-Monte-Carlo-Simulator#2]
Hello, I am trying to change the HgCdTe device parameters while changing your program to make it suitable for HgCdTe, but the result is completely opposite to the experiment. For example, after I increase the length of the multiplication zone, the gain increases instead. I don’t know why, if you can give me some guidance, I would be very grateful

**Comment by jdpetticrew** [comment]
Sorry, unable to help I have no experience with HgCdTe detectors or their scattering mechanisms. For general debugging, check your efield profiles (can pull from the device.profiler()), then check impact ionisation coefficients generated are as expected.
